service: shared-api-gateway
provider:
  name: aws
  profile: default
  stage: dev
  region: ap-southeast-2
  apiGateway:
    restApiId: 
      Ref: SharedApiGw
    restApiRootResourceId:
      Fn::GetAtt: 
        - SharedApiGw # Optional
        - RootResourceId 
    restApiResources:
      hello: 
        Ref: Hello
package:
  individually: true
  excludeDevDependencies: true
functions:
  hello: # A Function
    handler: handler.hello # The file and module for this specific function.
    description: hello world function # The description of your function.
    runtime: nodejs6.10 # Runtime for this specific function. Overrides the default which is set on the provider level
    package:
      include: # Specify the directories and files which should be included in the deployment package for this specific function.        
        - handler.js
        - package.json
        - package-lock.json
      exclude: # Specify the directories and files which should be excluded in the deployment package for this specific function.
        - .git/**
        - serverless.yml
    events: # The Events that trigger this Function
      - 
        http: # This creates an API Gateway HTTP endpoint which can be used to trigger this function.  Learn more in "events/apigateway"
          path: hello # Path for this endpoint
          method: get # HTTP method for this endpoint
          cors: true # Turn on CORS for this endpoint, but don't forget to return the right header in your response
resources: # you can add CloudFormation resource templates here
  Resources:
    SharedApiGw:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: SharedApiGateway.${self:provider.region}
    Hello:
      Type: AWS::ApiGateway::Resource
      Properties:
        RestApiId: 
          Ref: SharedApiGw
        PathPart: hello
        ParentId: 
          Fn::GetAtt:
            - SharedApiGw
            - RootResourceId
  Outputs:
    apiGatewayRestApiId:
      Value:
        Ref: SharedApiGw
      Export:
        Name: sharedApiGateway-restApiId
    apiGatewayRestApiRootResourceId:
      Value:
         Fn::GetAtt:
          - SharedApiGw
          - RootResourceId
      Export:
        Name: sharedApiGateway-rootResourceId
